### PR TITLE
Parse tank name

### PR DESCRIPTION
**Pull request by enjinabner**

### CODE REVIEW

**Review by leonardocustodio — CHANGES_REQUESTED** [review]
I will comment on this one by the end of the day

**Review by v16Studios — APPROVED** [review]

**Comment by leonardocustodio** [comment]
So I believe what we should do here is to translate and save the name already in the utf8 format instead of hex.
If we take a look at our database at FuelTanks table the name is in ut8 format the same for attributes key/values.
So to keep it consistent I think we should save that in the events table as ut8 too.... This means the change should be done in the ingest parser

**Comment by enjinabner** [comment]
> So I believe what we should do here is to translate and save the name already in the utf8 format instead of hex. If we take a look at our database at FuelTanks table the name is in ut8 format the same for attributes key/values. So to keep it consistent I think we should save that in the events table as ut8 too.... This means the change should be done in the ingest parser

Do we need to patch old data?

**Comment by leonardocustodio** [comment]
This is a good question. Usually the answer would be yes, but since it was old events, it would make sense to have the old values. I mean the value is whatever it was when it was created. Just like the blockchain, when you do a migration, if you query older blocks the values will still be the old values. So I guess in this case, we don't really need to patch the old data.

**Review by v16Studios — APPROVED** [review]

**Review by leonardocustodio — APPROVED** [review]

**Pull request merged**
